version: "3.6"
services:
  service:
    image: docker-demo:latest
#    build:
#      dockerfile: Dockerfile
    ports:
      - "8080:9090"
    depends_on:
      - "influxdb"


  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"


  influxdb:
    image: "influxdb:1.6.2"
    ports:
      - "8086:8086"
    environment:
      - "INFLUXDB_DB=jmx"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=123456"
